In [1]:
import numpy as np
import scipy as sp

In [2]:
from scipy import signal

from scipy import linalg
import numpy as np
from openpiv.pyprocess import fft_correlate

x = [[1 , 0 , 0 , 0] , [0 , -1 , 0 , 0] , [0 , 0 , 3 , 0] , [0 , 0 , 0 , 1],[0,0,2,0]]
x = np.array(x)
y = [[4 , 5] , [3 , 4]]
y = np.array(y)

# x = np.random.rand(2,3)
# y = np.random.rand(4,6)

print("x:\n", x)
print("y:\n", y)

print ("conv:\n" ,  signal.convolve2d(x , y , 'full'))

s1 = np.array(x.shape)
s2 = np.array(y.shape)

size = s1 + s2 - 1


fsize = 2 ** np.ceil(np.log2(size)).astype(int)
fslice = tuple([slice(0, int(sz)) for sz in size])


new_x = np.fft.rfft2(x , fsize)


new_y = np.fft.rfft2(y , fsize)
result = np.fft.irfft2(new_x*new_y)[fslice].copy()

print("fft for my method:\n" , np.array(result.real, np.int32))

print("fft:\n" , np.array(signal.fftconvolve(x ,y,'full'), np.int32 ))

print("openpiv:\n", fft_correlate(x,y[::-1,::-1]).astype(np.int32))

print("circular: \n " ,np.array(np.fft.irfft2(np.fft.rfft2(x,size)*np.fft.rfft2(y,size))).astype(np.int32))

x:
 [[ 1  0  0  0]
 [ 0 -1  0  0]
 [ 0  0  3  0]
 [ 0  0  0  1]
 [ 0  0  2  0]]
y:
 [[4 5]
 [3 4]]
conv:
 [[ 4  5  0  0  0]
 [ 3  0 -5  0  0]
 [ 0 -3  8 15  0]
 [ 0  0  9 16  5]
 [ 0  0  8 13  4]
 [ 0  0  6  8  0]]
fft for my method:
 [[ 4  5  0  0  0]
 [ 3  0 -5  0  0]
 [ 0 -3  7 15  0]
 [ 0  0  9 16  5]
 [ 0  0  8 13  4]
 [ 0  0  6  8  0]]
fft:
 [[ 3  5  0  0  0]
 [ 2  0 -4  0  0]
 [ 0 -2  7 14  0]
 [ 0  0  9 16  5]
 [ 0  0  8 13  3]
 [ 0  0  6  8  0]]
openpiv:
 [[ 4  5  0  0  0]
 [ 3  0 -5  0  0]
 [ 0 -3  7 15  0]
 [ 0  0  9 16  5]
 [ 0  0  8 13  4]
 [ 0  0  6  8  0]]
circular: 
  [[ 5  4  0  0]
 [ 3 -2 -3  0]
 [-2  0 17  6]
 [ 0  2 17 11]
 [ 0  2 14  8]
 [-1  1 10  3]]


In [19]:
x = np.ones((2,2))
np.pad(x,np.round(np.array(x.shape)/2).astype(np.int))

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.round(np.array(x.shape)/2)

array([2., 2.])